apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: admin-github
  annotations:
    github.com/project-slug: mattjmorrison-homelab/admin-github
spec:
  type: iac
  owner: mattjmorrison-homelab
  lifecycle: experimental
  system: automation
